"""create downloaded files table

Revision ID: 4b8393d3850d
Revises: f900696c536c
Create Date: 2026-07-23 12:10:44.914704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4b8393d3850d'
down_revision: Union[str, Sequence[str], None] = 'f900696c536c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('downloaded_files',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=1000), nullable=False),
    sa.Column('statistics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('downloaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['download_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'file_name', name='uq_downloaded_files_job_id_file_name')
    )
    op.create_index(op.f('ix_downloaded_files_job_id'), 'downloaded_files', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_downloaded_files_job_id'), table_name='downloaded_files')
    op.drop_table('downloaded_files')
    # ### end Alembic commands ###
